### ISSUE TITLE
Nicely done

### ISSUE THREAD

**Issue by Mogeiman** [xTRUMANx/zapi#2]
I don't think Zaad has an API yet, which is crazy cus it has been so long. If you did this 9 years ago, I think you should've contacted them about making an official one. It would be so wonderful for local Businesses as it would open the doors for Online shopping. I think there is a 3rd party called WaafiPay now that has made one for the EVC services.

**Comment by xTRUMANx** [comment]
They do have an API, but they're kinda stingy with it. The code in this repo no longer works cause it crawled their old website which is no longer up.

Good news is their new website is based on angular which communicates with an API. I already made an app using their new API but I'd advise anyone interested in using their API for business purposes to get in touch with them directly rather than doing it under the radar.

**Comment by Mogeiman** [comment]
Wow I didn't know they had one. What is your app called and did you make your app with the official one?

**Comment by xTRUMANx** [comment]
It's not a published app. Would probably be unwise to publish an app that expects people to enter their Zaad credentials to see their info.

It's more of a proof-of-concept. I haven't used it in a while but all the endpoints I've implemented still work except for the "activity report". Here's a screenshot:

![image](https://user-images.githubusercontent.com/1555680/227214140-a39eac28-d0ad-4e1e-9d8b-dc652b1f8a7f.png)

If you're interesting in making your own, head over https://myaccount.telesom.com and open the network  tab of your browser's dev tools and start pressing buttons.

**Comment by Mogeiman** [comment]
Sure I will look into it
